### ISSUE TITLE
Example patch graph link returns "403 forbidden"

### ISSUE THREAD

**Issue by positlabs** [cables-gl/8thWall#6]
From the readme: https://cables.gl/edit/cmXoMS
<img width="436" alt="Screen Shot 2020-10-30 at 1 06 58 PM" src="https://user-images.githubusercontent.com/1918844/97735521-d2e94000-1ab0-11eb-9a6d-25cb89e76d47.png">

**Comment by seacloud9** [comment]
I am experiencing this as well @steam0r I think this patch might be private.  I would personally really like to see an example with 8thwall

Thanks
